# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
- main

pool:
  name: default

steps:

  - task: AzureContainerApps@1
    inputs:
      azureSubscription: 'Visual Studio Professional with MSDN(f550eeac-1a97-47aa-9a8c-d764ecde8d8d)'
      imageToDeploy: 'acraz2003mh251006.azurecr.io/aspnetcorecontainer:latest'
      containerAppName: 'aca-az2003'
      resourceGroup: 'rg-dev-applied-skills-aca-02-final-test'